### ISSUE TITLE
H&K G36 wielded overlay incorrect

### ISSUE THREAD

**Issue by Olaroll** [SomeDeadGuy/UndeadPeopleTileset#1]
When holding an H&K G36 <sub>hk_g36</sub>  it doesn't show the overlay version of the weapon sprite, as shown in the attached image.

It might be worth considering if this issue could extend to other weapons as well. I myself am unsure as I haven't tested and don't know much about how tilesets work.

![cataclysm-tiles_2020-03-28_10-31-35](https://user-images.githubusercontent.com/13151772/77819275-458cda00-70e2-11ea-89d0-ecd6df9fb8dc.png)

**Comment by SomeDeadGuy** [comment]
Fixed!
