### ISSUE TITLE
Feral humans don't have a sprite, show up as @

### ISSUE THREAD

**Issue by Hulkninja** [SomeDeadGuy/UndeadPeopleTileset#10]
![feral](https://user-images.githubusercontent.com/61886819/86975750-46211c00-c179-11ea-80ad-292f94d4fb48.png)

Just like the title says. Was playing the "Ambush" start and wondered why there were "@" characters beating the snot out of me.
Picture for clarity's sake. The monster is called "Feral Human".

**Comment by SomeDeadGuy** [comment]
Bastard! They were just friggin added in to the game today!
What i am, some sort of Flash of Tilesets?
Actually i am and they were just added in to tileset. :)
