### ISSUE TITLE
Tiles missing from NEW but working in Legacy

### ISSUE THREAD

**Issue by Yurameki** [SomeDeadGuy/UndeadPeopleTileset#16]
Related to #11 these tiles are also missing:

155 mm Howitzer
Banshee
Little Zombie Queen
Zombie Queen
Nemesis
Chimera

There's probably more, I'll update when I find them.

**Comment by SomeDeadGuy** [comment]
This is stuff from a mod.
Ofcourse it is missing.

**Comment by Yurameki** [comment]
Sure, but I have all the mod bits installed from the pack and they existed just fine in Legacy. So I posted them as someone on the forums asked.

**Comment by Yurameki** [comment]
Howitzer is from Blaze Industries which is a remake of the Blaze mod
Zombie Queen, Little Zombie Queen, Chimera and Nemesis are Nechronica Redux, so far it looks like mostly those two mods, I'll keep my eyes open for any others.

**Comment by Goodgulf-PL** [comment]
Howitzer is not in Blaze mod but in Tankmod Revived.

**Comment by Yurameki** [comment]
> Howitzer is not in Blaze mod but in Tankmod Revived.

Oops, good call!

**Comment by SomeDeadGuy** [comment]
for necronica use my fork or wait when original author updates it

**Comment by SomeDeadGuy** [comment]
Necronica mod was updated.

**Comment by SomeDeadGuy** [comment]
I think everything in here is fixed.
