### ISSUE TITLE
Missing car/shopping carts tiles

### ISSUE THREAD

**Issue by CHJKDM51** [SomeDeadGuy/UndeadPeopleTileset#19]
Soo it worked perfect till b10920 but since b10923 and newer car's quarterpanels not drawing at all. I also noticed some shopping carts missing tiles now.
![Graphical error](https://user-images.githubusercontent.com/58046029/90578799-dddc4600-e1cc-11ea-9770-d0297eaaddea.png)

**Comment by macrosblackd** [comment]
b10922 had a huge change to the way panels are defined - I rolled back to 10921 and everything worked again.
