### ISSUE TITLE
Cargo Shelving is missing a tile

### ISSUE THREAD

**Issue by DoctorVanGogh** [SomeDeadGuy/UndeadPeopleTileset#23]
The [new-ish](https://github.com/CleverRaven/Cataclysm-DDA/pull/39757/commits/9baeaa606b9c4844996a4dc86dbd5469aa9df783) vehicle part "Cargo Shelving" [`cargo_rack_extended` (?)]  (1000L non boardable storage) from blaze is missing a tile icon:

![image](https://user-images.githubusercontent.com/324067/92094776-1ab35a00-edd5-11ea-9974-d3e305cfa224.png)

Suggestion:
Maybe reuse `f_rack` ?
![image](https://user-images.githubusercontent.com/324067/92096234-ee98d880-edd6-11ea-9561-70e333adc785.png)

Would turn the vehicle into into 
![image](https://user-images.githubusercontent.com/324067/92096310-0708f300-edd7-11ea-8826-8eead7285b3e.png)

or even shift color tones to match the cargo baskets?

![image](https://user-images.githubusercontent.com/324067/92096551-4fc0ac00-edd7-11ea-976c-95e5dd38b67e.png)
(total hack-job - there's a reason I tend to not do "pixels" :grin:)

**Comment by SomeDeadGuy** [comment]
added
