### ISSUE TITLE
MetalMaster Forge Buddy Missing Icon(Aftershock)

### ISSUE THREAD

**Issue by Mallowdust** [SomeDeadGuy/UndeadPeopleTileset#26]
Hello! These two item from the Aftershock mod with the following name and ID are missing  images and instead shows up as a red / yellow "&" signs. Thanks for all your work :) 

Mod: Aftershock

    "id": "afs_metal_rig",
    "name": { "str": "MetalMaster forge buddy" },

"id": "afs_kitchen_rig",
    "copy-from": "vehicle_rig",
    "name": { "str": "KitchenMaster cooking buddy", "str_pl": "KitchenMaster cooking buddies" },

**Comment by SomeDeadGuy** [comment]
Sorry for late responce. Will be fixed today.
