### ISSUE TITLE
problem with tileset and quarterpanels

### ISSUE THREAD

**Issue by cresttoothpaste** [SomeDeadGuy/UndeadPeopleTileset#28]
![image](https://user-images.githubusercontent.com/71830563/94150531-40b5a280-fe47-11ea-9590-4d54cbfc8610.png)

So I have an issue with of all things, quarterpanels.  They've been replaced by a text box with "something here" written in.  Secondly, it seems a lot of tables are rotated either left or right by 90 degrees.

**Comment by SomeDeadGuy** [comment]
You using Legacy Version.
It is outdated.
