### ISSUE TITLE
heavy-duty rear lights missing

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [SomeDeadGuy/UndeadPeopleTileset#29]
Could you take a look at "heavy-duty" rear lights. They somehow disappeared along the way.  Normal cars are fine.

BTW - thanks a lot for this beautiful tileset!

![grafik](https://user-images.githubusercontent.com/44737997/95586746-65ae3600-0a41-11eb-93df-93a986426978.png)

**Comment by SomeDeadGuy** [comment]
It is missing for a reason.
It will show up in places it shouldn't. Especially in Tank mod Revived
I decided to remove it.

**Comment by Pupsi-Mupsi** [comment]
Thanks. I did not know that. Have a great evening.
