### ISSUE TITLE
icons missing from new version that used to exist

### ISSUE THREAD

**Issue by cresttoothpaste** [SomeDeadGuy/UndeadPeopleTileset#30]
So after sniffing around a good while, I have noticed that none of the golems, demon spiders, nor vehicle shelves (of all things) no longer have sprites.  I know they used to have thier own graphics, but now they are just ascii.  Should I switch to legacy or something?

**Comment by SomeDeadGuy** [comment]
you should use mod with tiles for magiclysm
plug it in during world generation or edit mods.json for your existing save

comeback to me if you have problems

**Comment by cresttoothpaste** [comment]
![image](https://user-images.githubusercontent.com/71830563/95792199-f50d5080-0cb0-11eb-9e2b-d936076f0def.png)
This is my mod list.

I have the magic overmap mod, but still no luck

**Comment by SomeDeadGuy** [comment]
No it is not :)
Check installation instructions ONCE AGAIN!

**Comment by cresttoothpaste** [comment]
Okay, so i reread the instructions, and saw the problem on that end.

![image](https://user-images.githubusercontent.com/71830563/95858606-5540d880-0d2b-11eb-893a-bef9c7b12db3.png)

So, i loaded up a new game and fresh world with those gfx mods put in, and i spawned 3 golems and the spider again.

![image](https://user-images.githubusercontent.com/71830563/95858496-317d9280-0d2b-11eb-8bf1-f7ec38d03cf5.png)

The flesh golem has a sprite now, but none of the others do.

Am I blind with the instructions? i put the mod folder in the main cdda install folder.

![image](https://user-images.githubusercontent.com/71830563/95858803-a4870900-0d2b-11eb-96af-09a4ee24e955.png)

**Comment by SomeDeadGuy** [comment]
Are you using launcher?
In that case you probably have two cataclysm folders. And you putting mods folder in one, but launch the game from another. It is a common problem with launcher users.

**Comment by cresttoothpaste** [comment]
It must have been the world reset that did it, because now all of the golems and the spider have sprites again.  Thank you a ton for both your time and this awesome tileset!

**Comment by SomeDeadGuy** [comment]
Cool!
