### ISSUE TITLE
No Sprite for Rotting Wolf Man From Magiclysm

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#32]
There is no sprite for the Rotting Wolf Man. 
If there is anywhere else to suggest new sprites, please notify me and i will submit my suggestion there.

**Comment by SomeDeadGuy** [comment]
Here is fine.

**Comment by Theawesomeboophis** [comment]
Thanks for replying, I didn't know, I appreciate it.

**Comment by Theawesomeboophis** [comment]
I see a new sprite in magiclysm, Is that Wolf Man sprite?
want to know so I can close this

**Comment by Theawesomeboophis** [comment]
Sprite was added, loads properly(both versions).
