### ISSUE TITLE
No Support for  Vampiric Stuff Mod in New Version

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#33]
There Is no support for Vampiric Stuff and Vampiric Stuff+Arcana(Medieval Mod Reborn removed from issue due to SDG adding support, thanks btw).

**Comment by SomeDeadGuy** [comment]
Are you talking about Medieval Mod Reborn by chaosvolt?

**Comment by Theawesomeboophis** [comment]
Yes, and Vampiric Stuff+Arcana as well as normal Vampiric Stuff

**Comment by Theawesomeboophis** [comment]
"dda",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "DinoMod",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "sees_player_hitbutton",
  "sees_player_retro",
  "my_sweet_cataclysm",
  "crazy_cataclysm",
  "aftershock",
  "secronom",
  "Arcana",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "Medieval_Mod_Reborn",
  "MMA",
  "PK_REBALANCE",
  "Cata++",
  "more_survivor_stuff",
  "fuji_mpp",
  "Bootleg_Walkers",
  "AftershockUDP",
  "ArcanaUDP",
  "BlazeIndustriesUDP",
  "crt_expansionUDP",
  "CrazyCataclysmUDP",
  "DinoModUDP",
  "MagiclysmUDP",
  "My_Sweet_CataclysmUDP",
  "MMAUDP",
  "PK_REBALANCE_UDP",
  "secronom_UDP",
  "zets_hair_extensions_undead",
  "Cata++UDP",
  "Arts' Guns",
  "Dorf_Life",
  "Dorf_LifeUDP",
  "fallout",
  "Fallout_CDDA_UDP",
  "Arts' GunsUDP",
  "WHALEYHAIR_UDP",
  "collectablemod",
  "BL9_100monres"
Here is a list of my mods, as you can see, the only one's that seem to be unsupported are Medieval Mod Reborn And Vampiric Stuff as well as the Arcana expansion, All other mods either have a mod tileset here or are supported through Goat God Compilation versions.

**Comment by Theawesomeboophis** [comment]
Dorf Life and one of the tattoo mods were made compatible through file editing.

**Comment by Theawesomeboophis** [comment]
Also, as a side question, are there any plans to make Bootleg Walker sprites?

**Comment by Theawesomeboophis** [comment]
What do you use to make sprites, thinking about contributing some tiles but don't know how to make them.

**Comment by SomeDeadGuy** [comment]
And feel free to join my discord server. That way i will answer your question way faster.

**Comment by SomeDeadGuy** [comment]
I use Aseprite

**Comment by Theawesomeboophis** [comment]
Ok thanks.

**Comment by Theawesomeboophis** [comment]
I'll get aseprite on steam so then I can contribute to the tileset.

**Comment by Theawesomeboophis** [comment]
Discords not really my thing, I'll just submit stuff here, if that's ok.

**Comment by SomeDeadGuy** [comment]
You can also add and change tiles. This is where i keep tilesets unpacked before building them with a script. https://github.com/SomeDeadGuy/UndeadPeopleUnpacked

**Comment by Theawesomeboophis** [comment]
Ok, I'll try and make some tiles.

**Comment by Theawesomeboophis** [comment]
Thanks.
