### ISSUE TITLE
Cata++ broken enemy sprites.

### ISSUE THREAD

**Issue by DenJur** [SomeDeadGuy/UndeadPeopleTileset#34]
A lot of enemy sprites for the submod seem to be broken (display as piece of UltiCa). Tested a bunch of "augmented" enemies.

![ultica](https://user-images.githubusercontent.com/6560293/97721549-7a6e6e80-1ac1-11eb-9a59-da3d2e66addf.png)
![udp](https://user-images.githubusercontent.com/6560293/97721554-7cd0c880-1ac1-11eb-9329-04c13114dd7b.png)

**Comment by Theawesomeboophis** [comment]
Are you using Legacy Or New Version? because legacy is outdated.

**Comment by Theawesomeboophis** [comment]
I found a temporary solution, switch back to legacy because this is only a problem with new version.

**Comment by DenJur** [comment]
New version

**Comment by Theawesomeboophis** [comment]
Switch to Legacy version until fix arrives, as this is a problem with new
version.

**Comment by Theawesomeboophis** [comment]
This is my email btw, my account name is Theawesomeboophis.

**Comment by Theawesomeboophis** [comment]
can you try to find what's causing it, I might be able to fix it and submit a pull request.

**Comment by DenJur** [comment]
Ok, had a bit of time to look into this and it looks like the issue was from using Cata++ version from TheGoatGod mod pack. "UNDEAD_PEOPLE_BASE" was added to compatible list in the tileset config. Looks like it was fixed couple of days ago. They now ship copy of this tileset so I guess it's not recommended to use the CataUDP if you source Cata++ from that repository.

**Comment by Theawesomeboophis** [comment]
Should I submit this problem to Goat God?

**Comment by Theawesomeboophis** [comment]
Are you talking about update from 7 days ago and does it fix problem, because I am having same problem.

**Comment by DenJur** [comment]
Yes, I don't see a problem with that version anymore. Version I had was extending compatibility list for Cata++ tiles and did not ship UDP tiles. The current one does.

**Comment by Theawesomeboophis** [comment]
Thanks, been having same problem, gonna update.
