### ISSUE TITLE
All Shockers except Skeletal shocker invisible on new version

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#35]
Only skeletal shocker appears in my game, all others are still invisible, tested multiple times with all versions of Arcana, problem still persist.

**Comment by Theawesomeboophis** [comment]
Might be connected to https://github.com/SomeDeadGuy/UndeadPeopleTileset/issues/31.

**Comment by SomeDeadGuy** [comment]
please make new folder with cataclysm
only install cataclysm there and arcana from Kenan's mod pack
i tested arcana multiple times now and all shockers show up as they should

**Comment by Theawesomeboophis** [comment]
You mean create new folder in cataclysm directory just for mod tilesets?

**Comment by Theawesomeboophis** [comment]
Like I did for Goat God mods, putting them in a separate folder within mods.

**Comment by SomeDeadGuy** [comment]
No
Creating completly new game folder in different place
http://dev.narc.ro/cataclysm/jenkins-latest/Windows_x64/Tiles/ - latest 64bit version
install unpack it in anywhere
and install Kenan mod pack on top of it https://github.com/Kenan2000/CDDA-Kenan-Modpack
and then my tileset
with Kenan modpack there is no need to use mod tileset, cause it is already in the mod

**Comment by SomeDeadGuy** [comment]
![h6OdqVKh](https://user-images.githubusercontent.com/37592026/98714873-77fdf580-239a-11eb-88e4-51021a28fa90.jpg)

**Comment by Theawesomeboophis** [comment]
What does that mean?

**Comment by SomeDeadGuy** [comment]
Me waiting when you do what i described above.

**Comment by Theawesomeboophis** [comment]
Will installing on a different hard drive have the same effect?

**Comment by Theawesomeboophis** [comment]
Also, will I keep my mods and presets if I do what is described above?

**Comment by Theawesomeboophis** [comment]
Gonna try installing on my other hard drive.

**Comment by Theawesomeboophis** [comment]
Reinstalled, still no shockers except skeletal.

**Comment by Theawesomeboophis** [comment]
![Uploading [Johnathan]__14-45-45_Eastern Standard Time.png…]()

**Comment by Theawesomeboophis** [comment]
![Johnathan __14-45-45_Eastern Standard Time](https://user-images.githubusercontent.com/71793015/98825956-18880000-2403-11eb-990e-44b353d62ccb.png)

**Comment by Theawesomeboophis** [comment]
It may be hard to see because of Debug menu, how do I remove that in screenshots.

**Comment by Theawesomeboophis** [comment]
It seems that zappers and Secronom shocker variants load fine.

**Comment by Theawesomeboophis** [comment]
Finally fixed, but a new problem seems to have appeared, Whaley Hair and Tattoo tiles are invisible, going to reload before submitting issue though.

**Comment by Theawesomeboophis** [comment]
It seems issue may arise from Zets, not Whaley, definitely one of the hair mods.

**Comment by Theawesomeboophis** [comment]
Was fixed, but upon exiting game and restarting, problem reappeared.

**Comment by Theawesomeboophis** [comment]
Tested again, it seems that reloading the tileset makes the glitch reappear, I'm not quite sure why.

**Comment by Theawesomeboophis** [comment]
Switching from new to legacy to new again makes the glitch reappear as well.

**Comment by Theawesomeboophis** [comment]
Gonna reinstall tileset again and see if that fixes it.

**Comment by Theawesomeboophis** [comment]
Reinstalling tileset had no effect.

**Comment by SomeDeadGuy** [comment]
Okay, i have no idea what is happening.
I do not have this issue no matter what i install.
Please give me screenshot of mods what you are using in the world.
And link to all of those mods.
Or give me your whole folder with the game.

**Comment by Theawesomeboophis** [comment]
How do I give screenshot?

**Comment by Theawesomeboophis** [comment]
All of my mods are from Kenan modpack, except bl9 which was downloaded
separately.

**Comment by Theawesomeboophis** [comment]
[
  "dda",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "DinoMod",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "sees_player_hitbutton",
  "sees_player_retro",
  "my_sweet_cataclysm",
  "crazy_cataclysm",
  "aftershock",
  "secronom",
  "Arcana",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "Medieval_Mod_Reborn",
  "MMA",
  "PK_REBALANCE",
  "Cata++",
  "fuji_mpp",
  "Bootleg_Walkers",
  "AftershockUDP",
  "ArcanaUDP",
  "BlazeIndustriesUDP",
  "crt_expansionUDP",
  "CrazyCataclysmUDP",
  "DinoModUDP",
  "MagiclysmUDP",
  "My_Sweet_CataclysmUDP",
  "MMAUDP",
  "PK_REBALANCE_UDP",
  "secronom_UDP",
  "zets_hair_extensions_undead",
  "Cata++UDP",
  "Arts' Guns",
  "Dorf_Life",
  "Dorf_LifeUDP",
  "fallout",
  "Fallout_CDDA_UDP",
  "Arts' GunsUDP",
  "WHALEYHAIR_UDP",
  "collectablemod",
  "BL9_100monres",
  "Bootleg_WalkersUDP",
  "Medieval_Mod_RebornUDP",
  "vamp_stuff_UDP",
  "package_bionic_professions",
  "alt_map_key"
]

**Comment by Theawesomeboophis** [comment]
all mainline mods are from main game, rest are from Kenan modpack.

**Comment by Theawesomeboophis** [comment]
https://github.com/Kenan2000/CDDA-Kenan-Modpack 
https://github.com/Kenan2000/BL9

**Comment by Theawesomeboophis** [comment]
Bl9 was downloaded from launcher, but launcher uses that link to download.

**Comment by Theawesomeboophis** [comment]
I don't know why it's just skeletal shocker that appears, you would think all 3 would appear, there must be something different with skeletal shocker from the rest.

**Comment by Theawesomeboophis** [comment]
Fungal shocker also appears. It is only normal shocker and brute that don't appear, all others are working fine as far as I know.

**Comment by Theawesomeboophis** [comment]
All sprites in Legacy work as intended, which is why I believe it may be a problem with how New Version loads these specific sprites, and not a problem with a specific mod tileset.

**Comment by SomeDeadGuy** [comment]
no, it is error with mod tileset
in one or two of them there is shockers set for 32x32 which conflicts with64x80 versions

**Comment by SomeDeadGuy** [comment]
look like there is some shocker data in PK Rebalancing mod!
Wait for update for kenan modpack, my tileset is already fixed, but will not work untill main mod is updated.

**Comment by Theawesomeboophis** [comment]
Ok, thanks, I realized those sprites in Pk rebalance when original issue was posted, didn't know if they would cause an issue or not, gonna update.

**Comment by Theawesomeboophis** [comment]
Shocker brute reappeared, but I found that regular shocker sprite is in Secronom Large.png, which is making it invisible still, rest work though. Just remove that from secronom large.png and this bug should be completely gone.

**Comment by Theawesomeboophis** [comment]
I'm not talking about the red secronom variants, leave those, but there is a default shocker zombie sprite in large.png

**Comment by Theawesomeboophis** [comment]
Nevermind, actual problem is in Crazy Cataclysm normal.png, secronom might cause problem, but it's not the culprit of the regular shocker being invisible, Crazy Cataclysm is.

**Comment by Theawesomeboophis** [comment]
Removing the sprite from crazy cataclysm fixed it, how do I close the white gap between sprites, once I learn how to close that gap I can send it to you.

**Comment by Theawesomeboophis** [comment]
![CrazyCataclysm_normal](https://user-images.githubusercontent.com/71793015/99004937-e31c0900-250d-11eb-8b10-d6854342ba7d.png)
Fixed Version.

**Comment by Theawesomeboophis** [comment]
![CrazyCataclysm_normal](https://user-images.githubusercontent.com/71793015/99005194-5b82ca00-250e-11eb-8d0a-6119dc5e36b8.png)
Before.

**Comment by Theawesomeboophis** [comment]
Spacing between sprites might be wrong, also might have cut off a tiny piece or something, using the default png editor for this was difficult because it kept moving the sprites in pieces.

**Comment by Theawesomeboophis** [comment]
Might want to remove electric zombie corpse in between Mr skeletal and dead fungus, but corpse has no effect because it's dead and not animated anyways, so It's your choice really.

**Comment by Theawesomeboophis** [comment]
Also removed electric zombie lines from mod_tileset.json.

**Comment by Theawesomeboophis** [comment]
Sent fix in pull request.

**Comment by Theawesomeboophis** [comment]
Hope I did this properly.

**Comment by Theawesomeboophis** [comment]
Don't know if you accept pull request here.

**Comment by SomeDeadGuy** [comment]
Aha, i see.
No, this is wrong. All tiles edited here
https://github.com/SomeDeadGuy/UndeadPeopleUnpacked
After they are generated via script and upload over here.
I do not acept any pull requests here, because it os not a place for it. 
I will delete shocker myself from CrazyCataclysm unpacked version later.

**Comment by Theawesomeboophis** [comment]
Ok, thanks.

**Comment by Theawesomeboophis** [comment]
Also it appears that Jolt sprite in secronom large.png is causing a minor issue, doesn't appear invisible like others, but does appear unanimated.

**Comment by SomeDeadGuy** [comment]
Well, there is no issue there. It is not animated. 😂
But i get it. I will look at it. :)

**Comment by Theawesomeboophis** [comment]
Oh, I thought it was animated, my mistake.

**Comment by SomeDeadGuy** [comment]
Well, now it will be. :)

**Comment by Theawesomeboophis** [comment]
Thanks, gonna close this now.
