### ISSUE TITLE
Dinomod: Obscure Dinos and Mosasaurus Sprites

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#36]
Currently there is no sprite for mosasaurus, I believe adding one will beneficial in the future as there seems to be plans to add more plesiosaurs, and I added nothronychus to this issue because I'm interested to see what it would look like in cataclysm and also I did not want to open a separate Issue just for the Nothronychus sprite.

**Comment by Theawesomeboophis** [comment]
Obscure dinos almost finished, name has been updated to include those sprites as well.

**Comment by SomeDeadGuy** [comment]
Added those. Closing this. More dinos to come. Please do not create new issues about it. Rest will be added in due time.

**Comment by Theawesomeboophis** [comment]
Ok, I apologize, I was unaware they were added. Thank you.

**Comment by SomeDeadGuy** [comment]
Oh no, i added them today. No problem. It just i know there is a ton of dinos not having unique tiles. I will add them eventually. It will take some time.

**Comment by Theawesomeboophis** [comment]
Thank you for your work, I truly appreciate it, I will try to get aseprite
in the future and directly contribute.
