### ISSUE TITLE
Zets-Hair-Extensions_Undead keeps mutating hair/beard/JPeyes instead of real mutations

### ISSUE THREAD

**Issue by MrOlaf** [SomeDeadGuy/UndeadPeopleTileset#4]
I resolved this issue by adding lines "profession": true, in beards.json for each beard, probably would have to do the same for hair.json but I deleted it along with the JP stuff.

**Comment by SomeDeadGuy** [comment]
please see if it fixed

**Comment by MrOlaf** [comment]
Please consider it as resolved. I tested by debugging and using mutagen serum x50 to see if there were no hair color/ hair type / eye color/ eye type/ beard color /beard type/ skin color mutations. Thanks for the fix.
