### ISSUE TITLE
No snow?

### ISSUE THREAD

**Issue by adamkad1** [SomeDeadGuy/UndeadPeopleTileset#40]
So i recently switched from deadpeople to undeadpeople and everything seems fine besdies the fact that snowy white tiles changed to normal green grass tiles in my save, and i dunno what can be wrong

**Comment by SomeDeadGuy** [comment]
Yes, there is no snow in the game.

**Comment by SomeDeadGuy** [comment]
When dev will add actual snow in the game i will draw it. Right now snow is not there, it just dirt and grass like in any other season.

**Comment by adamkad1** [comment]
> When dev will add actual snow in the game i will draw it. Right now snow is not there, it just dirt and grass like in any other season.

But tilesets like ultica give you white grass tiles in winter

**Comment by SomeDeadGuy** [comment]
They just draw grass in winter like snow.

**Comment by adamkad1** [comment]
well, if it works...

**Comment by SomeDeadGuy** [comment]
Someday devs will give us snow, man...

**Comment by adamkad1** [comment]
> Someday devs will give us snow, man...

yeah, and then we are going to boil it for even easier water

**Comment by DrPariah** [comment]
Don't worry, it will be ULTRA CONTAMINATED! With radiation! And Blob! And BLOB RADIATION! 
--
Sent from myMail for Android Tuesday, 15 December 2020, 11:27AM -06:00 from adamkad1  notifications@github.com :

**Comment by adamkad1** [comment]
But everything is allready contaminated with blob

**Comment by DrPariah** [comment]
But not like THIS! #REALISM
(just joking, you're basically right, there shouldn't be much difference between rain water and snow melt, shouldn't be any harder to get clean water out of it) 
--
Sent from myMail for Android Tuesday, 15 December 2020, 00:33PM -06:00 from adamkad1  notifications@github.com :
