### ISSUE TITLE
Tileset Error in Zone Manager with custom zoning

### ISSUE THREAD

**Issue by ToxiClay** [SomeDeadGuy/UndeadPeopleTileset#41]
For reasons unknown to man or beast, using a custom zone in the zone manager makes the Undead People (New Version) display a tileset error symbol.

![TilesetError](https://user-images.githubusercontent.com/13796683/102462274-8e414600-4017-11eb-8a5c-43aed9968e2c.png)

**Comment by SomeDeadGuy** [comment]
Yep. All tilesets have this error at the time.
Unless i will make this Error Graphics invisible.
What i need is ID for this zone, but i don't know what it is.

**Comment by ToxiClay** [comment]
From Cataclysm-DDA/data/json/loot_zones.json:

```
{
    "id": "LOOT_CUSTOM",
    "type": "LOOT_ZONE",
    "name": "Loot: Custom",
    "description": "Destination for loot with a custom filter that you can modify"
  },
```

**Comment by SomeDeadGuy** [comment]
Nope, this ID do not work.

**Comment by ToxiClay** [comment]
That's...bizarre. That's the only thing I can find for a custom zone designator.

**Comment by SomeDeadGuy** [comment]
Yeah. It is something contained in the game exe file or something.

**Comment by SomeDeadGuy** [comment]
error with the game, not with tileset
