### ISSUE TITLE
Cant start a new game with Aftershock loaded

### ISSUE THREAD

**Issue by 3NC3PH4L0ND1V3** [SomeDeadGuy/UndeadPeopleTileset#44]
DEBUG    : Error: Could not load image "data/mods//UnDeadPeople_mod_tileset_Aftershock/cancer.png": Couldn't open data/mods//UnDeadPeople_mod_tileset_Aftershock/cancer.png

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 861

Tried reinstalling the "UnDeadPeople_mod_tileset_Aftershock" folder but it had no effect.

**Comment by SomeDeadGuy** [comment]
What :l
cancer.png is tileset image for Five Nights at Freddy's mod
I will check it today

**Comment by SomeDeadGuy** [comment]
Okay, couple of things
I updated the game as always and it did not launched at all.
I deleted all files and reinstalled the game.
Now everything works, and aftershock seems to work.
I would suggest making completely clean install of the game.

**Comment by 3NC3PH4L0ND1V3** [comment]
Ahhh, thought i could get around that :/ but i guess its no use. Thanks bud, and merry christmas! Stay healthy <3 I'll let you know the result.

**Comment by 3NC3PH4L0ND1V3** [comment]
Yep, can confirm a fresh install solved it! Every mod is working from Aftershock to Zet's Hair Extension :) Only Secronom complained but it startet as well!

**Comment by SomeDeadGuy** [comment]
Yes, there is Animatronics mod, which adds Five Nights At Freddie's pizza place. Don't be confused.

**Comment by Theawesomeboophis** [comment]
> Yep, can confirm a fresh install solved it! Every mod is working from Aftershock to Zet's Hair Extension :) Only Secronom complained but it startet as well!

Secronom issue is not for mod tileset it is for mod itself.
