### ISSUE TITLE
JSON error with new update; won't launch

### ISSUE THREAD

**Issue by poppaflash** [SomeDeadGuy/UndeadPeopleTileset#45]
I guess the new experimental update broke the tileset, due to multitile something

![2020-12-24](https://user-images.githubusercontent.com/46941039/103078316-95300180-459f-11eb-9aa6-21fa98386afe.png)

**Comment by SomeDeadGuy** [comment]
Dude, update tileset and mod tilesets, and kenan modpack mods if you are using them.
Everything was fixed yesterday.

**Comment by poppaflash** [comment]
Ah shit, sorry. I'm new

**Comment by SomeDeadGuy** [comment]
No problem. After you sure error is fixed close this issue. 👍
