### ISSUE TITLE
Damaging cars sometimes show unknown tile graphics.

### ISSUE THREAD

**Issue by SomeDeadGuy** [SomeDeadGuy/UndeadPeopleTileset#47]
If someone know id of this tile please let me know.
Error occurs while zombie or the player smash any part of the vehicle for some time, or destroy one of car parts. After one turn unknown graphics disappears.
![unknown_damage_tile](https://user-images.githubusercontent.com/37592026/103207107-8bdfc580-490e-11eb-9bb0-c263b9328187.PNG)

**Comment by Theawesomeboophis** [comment]
Attempting to figure out ID of this tile, all I know is that it is a vehicular tile.

**Comment by Svankensen** [comment]
Could this be related?

https://github.com/CleverRaven/Cataclysm-DDA/issues/46727

**Comment by Theawesomeboophis** [comment]
It's possibly related, I'll watch that issue to see if the name of the
affected tiles appears.

**Comment by SomeDeadGuy** [comment]
Now it shows SOME graphics. Still not fixed but now it is completely the game issue.
