### ISSUE TITLE
Need more berets colors

### ISSUE THREAD

**Issue by ChewedGum** [SomeDeadGuy/UndeadPeopleTileset#48]
It's not exactly an issue, i'm not even sure if this is right place to ask, and it's more a proposition.
I just really wish there was more berets of different colors and shades and stuff. There is currently only one sprite for both wool/regular beret and it's grey-brown-ish, which is acceptable, but boring. It would be really cool if there was blue/black/red all those cool colors.

**Comment by SomeDeadGuy** [comment]
Only if there will be other beret items in the game.
I can in theory make a various colors, but then one berret will be changing color each time you load the game.
Not an issues for the tileset tho.
All i can recommed is create your own beret mod. :D
