### ISSUE TITLE
FEATURE: Animation is in the game now!

### ISSUE THREAD

**Issue by DillonSimeone** [SomeDeadGuy/UndeadPeopleTileset#5]
Check out this merge, in cause you haven't heard.

https://github.com/CleverRaven/Cataclysm-DDA/pull/40342

Hype! Swaying zombies! Giants breathing slowly! Grapplers waving their arms around! Eggheads dancing! Flowing water! Waving flames!

**Comment by SomeDeadGuy** [comment]
None of these is going to work! But is saw and already implemented some animation support.
Turrets will turn left and right. Update with them soon.
Closing this, if you don't mind.

**Comment by verate** [comment]
1. What are your requirements?
2. Can you give a bit more detail on what's missing in the current approach?
3. Can you post a sample animation that can't be implemented (or can't be implemented efficiently)?

**Comment by DillonSimeone** [comment]
https://imgur.com/Art77zW

So far, it seems not that hard to take apart sprites and animate them. This one is waving its pokey stabby thingy around! 

I've made a bunch so far... Still making more! Animate E.V.E.R.Y.T.H.I.N.G!

**Comment by SomeDeadGuy** [comment]
Yeah, i was more judgmental than necessary. It works. More animations soon.

**Comment by DillonSimeone** [comment]
Hell yeah! I've been using Sprite pro for the animations I made so far. Load up the sprite into a normal sprite editor or whatever, CHOP it up into pieces then throw all of the body parts into spriter pro and rig up a skeleton then fine-tune your animation. Click export and done! 

https://store.steampowered.com/app/332360/Spriter_Pro/

You can see the stuff I've made so far in this PR. https://github.com/pixel-32/CDDA-tileset/pull/38

I'm currently building a new patio deck in real life, so my animation madness is stalled for the time being!
