### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by apollovy** [SomeDeadGuy/UndeadPeopleTileset#50]
Hi there. Thank you for your work, it's awesome!
Do you have any license on your content? I'm asking because I've used your tileset to play first, made screenshots and then decided to port CDDA to iOS. https://www.notion.so/cdda/Cataclysm-Roguelike-RPG-be117cceaff94c2b97d0951b7c8036a8. And I use these screens for illustrations to a game, though I don't include your tileset together with the game itself.
Can I use it? Also I wanna use these screens to build small video and then maybe a gameplay video for app store to attract new players. What do you think?

**Comment by SomeDeadGuy** [comment]
I dunno what a licence is. And don't care enough to find out. :)
To use stuff from my tileset you don't need to ask me. Everyone can take and use it.

**Comment by SomeDeadGuy** [comment]
BTW I am not the original creator of many graphics in this tileset, I only maintain them.
