### ISSUE TITLE
Graphical Overmap Mod Issues

### ISSUE THREAD

**Issue by bouchacha** [SomeDeadGuy/UndeadPeopleTileset#52]
Hi,
I understand that Graphical Overmap mod (or at least a version of it) is included with this package. Is the one included sufficient or do we need to [download it separately?](https://github.com/Larwck/Graphical_Overmap) If so, what order do we install this? I tried installing the GO mod first, then installed UndeadPeople, and specifically followed the instructions about editing fonts.json. However, that pathway meant Cataclysm just would not start (nothing would happen when I click launch on the launcher). I have since tried installing only UndeadPeople (and created worlds with GO as a mod), but then it looks like this:

![image](https://user-images.githubusercontent.com/19356629/109401452-b563a000-7903-11eb-9a54-12dffcae5c63.png)

Any advice? I'm using the latest version of everything (downloaded just today). Thanks.

**Comment by SomeDeadGuy** [comment]
Did you placed map_font_LARWICK_SDG.png in to your cataclysm/font folder?

**Comment by bouchacha** [comment]
Yes. Although I will note that there are two 'font' folders:
1. cdda/data/font
2. cdda/font

When I take map_font_LARWICK_SDG.png found in UndeadPeople, do I need to make any edits to fonts.json? The readme.md is unclear on this point because as I read it, an edit to fonts.json is only needed for "some mods (PK, Arcana, Secronom) added!". Do we need to edit fonts.json if we intend to use Graphical Overmap (included in UndeadPeople) regardless of what other mods are used?

Edit: I figured out the issue. The readme.md instructions regarding what to replace in fonts.json don't have the end bracket ']'. That's what caused Cataclysm to fail to start. Admittedly it's my fault for overlooking it but it's easy to miss.

**Comment by SomeDeadGuy** [comment]
i will add end bracket in readme
yes, it would be better to add my map font

**Comment by SomeDeadGuy** [comment]
if it not fixed ping me here
