### ISSUE TITLE
Invisible cows

### ISSUE THREAD

**Issue by AlexisEssen** [SomeDeadGuy/UndeadPeopleTileset#55]
Hello, i am new to all this github stuff so go easy on me.
Well, the issue is in the title, the cows are invisible in the game. They do not appear in sprite-form, so to say, only when you mount them. You can interract with them still, like mount them and milk them, but they are invisible, only yellow or red ! appears near the place, where they suppose to be. Changing to other tilesets fixes this issue, i will add screenshots when i find cows in my current playthrough. Oh and when I mount them they do appear, but they go invisible when i dismount them.

**Comment by Theawesomeboophis** [comment]
Is everything installed correctly and in the right folder?

**Comment by SomeDeadGuy** [comment]
What mods are you using?

**Comment by SomeDeadGuy** [comment]
If you using Mutant Animals mod please redownload and reinstall tileset.

**Comment by AlexisEssen** [comment]
> What mods are you using?

A lot, but mutant animals is one of them, yes. But i will follow your advice and will tell the resutls, if you need them.

**Comment by Theawesomeboophis** [comment]
Another way to send your mods is to go to your world save in the cdda directory and enter mods.json and copy everything from there.

**Comment by AlexisEssen** [comment]
> Another way to send your mods is to go to your world save in the cdda directory and enter mods.json and copy everything from there.
Oh, thank you! As i said, i am new to this stuff, so yeah...

**Comment by Theawesomeboophis** [comment]
If you reply to quotes don't forget to press enter between the quote and the response, otherwise github includes the response as part of the quote.

**Comment by SomeDeadGuy** [comment]
Is this issue fixed?

**Comment by AlexisEssen** [comment]
> Is this issue fixed?

Nope, here is the screenshot. As you can see cows are actually invisible when in the line of sight and you can actually see the half-appearing sprite in the "shadow zone". Корова means Cow in russian. I did all that you told, re-installed tileset, mods to it, didn;t touch the fonts tho. 
![2233d](https://user-images.githubusercontent.com/43724648/112114612-507d2c00-8bc9-11eb-8237-f2141775252a.png)

**Comment by SomeDeadGuy** [comment]
Are you using mod with tiles for Mutant Animals?
I guess i did not fixed it. Redownload and reinstall again.

**Comment by AlexisEssen** [comment]
> Are you using mod with tiles for Mutant Animals?
> I guess i did not fixed it. Redownload and reinstall again.

Yes,i do. Ok, redownloading now

**Comment by AlexisEssen** [comment]
> Are you using mod with tiles for Mutant Animals?
> I guess i did not fixed it. Redownload and reinstall again.

I don't know if it's connected, but now game crashes every time on the tileset loading, same happens during the main menu option too.

**Comment by AlexisEssen** [comment]
> Are you using mod with tiles for Mutant Animals?
> I guess i did not fixed it. Redownload and reinstall again.

So. After i basically reisntalled Cata, installed the Kenan modpack first, and after that installed your tileset and modpack over that everything works and cows did appear. Thank you for quick response! 
![ssssd](https://user-images.githubusercontent.com/43724648/112165224-9b199b00-8bff-11eb-98d7-7a61ea090372.png)
