### ISSUE TITLE
missing texture near portal

### ISSUE THREAD

**Issue by ProvoGo** [SomeDeadGuy/UndeadPeopleTileset#56]
not sure what else to say
![uhm](https://user-images.githubusercontent.com/36768970/111911364-99b46b00-8a65-11eb-9f34-b0e9d0ee5b08.PNG)

**Comment by SomeDeadGuy** [comment]
Say what tileset are you using (how it called in the settings).
Say what mods are you using.
Say how this field named.
Say how this portal is named.

**Comment by SomeDeadGuy** [comment]
are you there?

**Comment by ProvoGo** [comment]
sadly i can only give the mods and tileset, i'm not sure where this

Tileset: UNDEAD_PEOPLE (NEW VERSION)

![active world mods, portal texture related](https://user-images.githubusercontent.com/36768970/112232073-3dee0b80-8c38-11eb-92af-726b611f5282.PNG)

**Comment by SomeDeadGuy** [comment]
Thank you for the info. I found the problem. 
It is "push_items" field. Never saw it appear in the game.
I summoned 50 tears in reality and none of them had this.
I will make new graphics for it. Redownload tileset on the next update tomorrow.

**Comment by SomeDeadGuy** [comment]
fix added to the tileset
