### ISSUE TITLE
On Load Errors

### ISSUE THREAD

**Issue by Ichthysdekilt** [SomeDeadGuy/UndeadPeopleTileset#59]
These were on the latest version of the tileset on 11543.  I stopped after a certain point because it was just too much.  I hope this is helpful in some way!
<img width="879" alt="Screenshot 2021-03-27 173944" src="https://user-images.githubusercontent.com/63475824/112735695-543fe400-8f24-11eb-95fe-f55433af3676.png">
<img width="890" alt="Screenshot 2021-03-27 173953" src="https://user-images.githubusercontent.com/63475824/112735696-543fe400-8f24-11eb-937b-3150372151f2.png">
<img width="891" alt="Screenshot 2021-03-27 174002" src="https://user-images.githubusercontent.com/63475824/112735697-543fe400-8f24-11eb-87a2-69ae4eb3c5de.png">
<img width="879" alt="Screenshot 2021-03-27 174011" src="https://user-images.githubusercontent.com/63475824/112735698-54d87a80-8f24-11eb-9b17-627502daeb6b.png">
<img width="881" alt="Screenshot 2021-03-27 174022" src="https://user-images.githubusercontent.com/63475824/112735699-54d87a80-8f24-11eb-87e9-b7d4c1fe17c3.png">
<img width="906" alt="Screenshot 2021-03-27 174032" src="https://user-images.githubusercontent.com/63475824/112735700-54d87a80-8f24-11eb-886d-cb8573354633.png">
<img width="913" alt="Screenshot 2021-03-27 174044" src="https://user-images.githubusercontent.com/63475824/112735701-54d87a80-8f24-11eb-979b-71ab0b89bff6.png">
<img width="884" alt="Screenshot 2021-03-27 174053" src="https://user-images.githubusercontent.com/63475824/112735702-54d87a80-8f24-11eb-8767-d1137e8b7720.png">
<img width="891" alt="Screenshot 2021-03-27 174101" src="https://user-images.githubusercontent.com/63475824/112735703-55711100-8f24-11eb-8be3-68ea74faa991.png">
<img width="1870" alt="Screenshot 2021-03-27 172714" src="https://user-images.githubusercontent.com/63475824/112735704-55711100-8f24-11eb-858a-51759dc0bc15.png">
<img width="1889" alt="Screenshot 2021-03-27 172724" src="https://user-images.githubusercontent.com/63475824/112735705-55711100-8f24-11eb-82c3-526e38d1aed2.png">
<img width="1894" alt="Screenshot 2021-03-27 172734" src="https://user-images.githubusercontent.com/63475824/112735706-55711100-8f24-11eb-947f-89b12a431b98.png">
<img width="1901" alt="Screenshot 2021-03-27 172747" src="https://user-images.githubusercontent.com/63475824/112735707-55711100-8f24-11eb-838c-78fce803642f.png">
<img width="1907" alt="Screenshot 2021-03-27 172757" src="https://user-images.githubusercontent.com/63475824/112735709-5609a780-8f24-11eb-86e1-f6df967c5082.png">
<img width="1916" alt="Screenshot 2021-03-27 172807" src="https://user-images.githubusercontent.com/63475824/112735711-5609a780-8f24-11eb-87f6-22a6e481be52.png">
<img width="1920" alt="Screenshot 2021-03-27 172818" src="https://user-images.githubusercontent.com/63475824/112735712-56a23e00-8f24-11eb-85ab-9a26f373de8b.png">
<img width="1907" alt="Screenshot 2021-03-27 172830" src="https://user-images.githubusercontent.com/63475824/112735713-56a23e00-8f24-11eb-849a-918b2cba887b.png">
<img width="1908" alt="Screenshot 2021-03-27 172843" src="https://user-images.githubusercontent.com/63475824/112735714-56a23e00-8f24-11eb-8eed-be3f343fc149.png">
<img width="1919" alt="Screenshot 2021-03-27 172857" src="https://user-images.githubusercontent.com/63475824/112735715-56a23e00-8f24-11eb-84e6-eb0e3fe3e787.png">
<img width="914" alt="Screenshot 2021-03-27 172914" src="https://user-images.githubusercontent.com/63475824/112735716-56a23e00-8f24-11eb-9713-f0f79a7bcf96.png">
<img width="909" alt="Screenshot 2021-03-27 172924" src="https://user-images.githubusercontent.com/63475824/112735717-573ad480-8f24-11eb-9a20-f0a98cae7210.png">
<img width="914" alt="Screenshot 2021-03-27 172934" src="https://user-images.githubusercontent.com/63475824/112735718-573ad480-8f24-11eb-91be-7faa5222f43f.png">
<img width="889" alt="Screenshot 2021-03-27 172943" src="https://user-images.githubusercontent.com/63475824/112735719-573ad480-8f24-11eb-8135-a21bf6da2d96.png">
<img width="893" alt="Screenshot 2021-03-27 172952" src="https://user-images.githubusercontent.com/63475824/112735720-573ad480-8f24-11eb-806b-6fea0c0244ad.png">
<img width="911" alt="Screenshot 2021-03-27 173001" src="https://user-images.githubusercontent.com/63475824/112735721-573ad480-8f24-11eb-97e8-3ca14db64d8d.png">
<img width="913" alt="Screenshot 2021-03-27 173013" src="https://user-images.githubusercontent.com/63475824/112735722-57d36b00-8f24-11eb-99b0-6b6530377459.png">
<img width="904" alt="Screenshot 2021-03-27 173023" src="https://user-images.githubusercontent.com/63475824/112735723-57d36b00-8f24-11eb-9e80-000b6171c315.png">
<img width="903" alt="Screenshot 2021-03-27 173032" src="https://user-images.githubusercontent.com/63475824/112735724-57d36b00-8f24-11eb-9ace-231affa59b0a.png">
<img width="898" alt="Screenshot 2021-03-27 173042" src="https://user-images.githubusercontent.com/63475824/112735725-57d36b00-8f24-11eb-9ab1-21a7e149fed3.png">
<img width="903" alt="Screenshot 2021-03-27 173053" src="https://user-images.githubusercontent.com/63475824/112735726-57d36b00-8f24-11eb-813d-f4a4296a82ad.png">
<img width="902" alt="Screenshot 2021-03-27 173102" src="https://user-images.githubusercontent.com/63475824/112735727-57d36b00-8f24-11eb-87e0-ede31c076dee.png">
<img width="910" alt="Screenshot 2021-03-27 173111" src="https://user-images.githubusercontent.com/63475824/112735728-586c0180-8f24-11eb-9ada-cb73bf3c0eee.png">
<img width="903" alt="Screenshot 2021-03-27 173121" src="https://user-images.githubusercontent.com/63475824/112735729-586c0180-8f24-11eb-9c99-bc5c24c8d499.png">
<img width="900" alt="Screenshot 2021-03-27 173130" src="https://user-images.githubusercontent.com/63475824/112735730-586c0180-8f24-11eb-871f-3e40ad761548.png">
<img width="911" alt="Screenshot 2021-03-27 173158" src="https://user-images.githubusercontent.com/63475824/112735731-586c0180-8f24-11eb-9593-28e70f1ccc01.png">
<img width="906" alt="Screenshot 2021-03-27 173209" src="https://user-images.githubusercontent.com/63475824/112735732-586c0180-8f24-11eb-80cf-3c738618273e.png">
<img width="902" alt="Screenshot 2021-03-27 173219" src="https://user-images.githubusercontent.com/63475824/112735733-59049800-8f24-11eb-9dc4-92512f9ef568.png">
<img width="904" alt="Screenshot 2021-03-27 173232" src="https://user-images.githubusercontent.com/63475824/112735734-59049800-8f24-11eb-8ca5-ec5ab44ff780.png">
<img width="896" alt="Screenshot 2021-03-27 173244" src="https://user-images.githubusercontent.com/63475824/112735735-59049800-8f24-11eb-8469-6bde9ed96d52.png">
<img width="901" alt="Screenshot 2021-03-27 173253" src="https://user-images.githubusercontent.com/63475824/112735737-59049800-8f24-11eb-8ad8-a150e1c4922c.png">
<img width="913" alt="Screenshot 2021-03-27 173301" src="https://user-images.githubusercontent.com/63475824/112735738-59049800-8f24-11eb-9c7f-c61e738c6776.png">
<img width="917" alt="Screenshot 2021-03-27 173310" src="https://user-images.githubusercontent.com/63475824/112735739-599d2e80-8f24-11eb-8053-79420b5f844d.png">
<img width="909" alt="Screenshot 2021-03-27 173319" src="https://user-images.githubusercontent.com/63475824/112735740-599d2e80-8f24-11eb-979b-069df8102cb0.png">
<img width="914" alt="Screenshot 2021-03-27 173330" src="https://user-images.githubusercontent.com/63475824/112735741-599d2e80-8f24-11eb-8db4-ad8627f4e208.png">
<img width="908" alt="Screenshot 2021-03-27 173340" src="https://user-images.githubusercontent.com/63475824/112735742-599d2e80-8f24-11eb-83f0-00b1c04e660c.png">
<img width="911" alt="Screenshot 2021-03-27 173358" src="https://user-images.githubusercontent.com/63475824/112735743-599d2e80-8f24-11eb-8564-58fdf743a8fe.png">
<img width="902" alt="Screenshot 2021-03-27 173406" src="https://user-images.githubusercontent.com/63475824/112735744-5a35c500-8f24-11eb-85d7-54b35dc580f6.png">
<img width="909" alt="Screenshot 2021-03-27 173417" src="https://user-images.githubusercontent.com/63475824/112735745-5a35c500-8f24-11eb-95e0-29730f293f61.png">
<img width="893" alt="Screenshot 2021-03-27 173427" src="https://user-images.githubusercontent.com/63475824/112735746-5a35c500-8f24-11eb-8b20-fef0d94f706a.png">
<img width="902" alt="Screenshot 2021-03-27 173436" src="https://user-images.githubusercontent.com/63475824/112735747-5a35c500-8f24-11eb-9019-026cd3a6551f.png">
<img width="902" alt="Screenshot 2021-03-27 173445" src="https://user-images.githubusercontent.com/63475824/112735748-5a35c500-8f24-11eb-8073-da1162420e9a.png">
<img width="908" alt="Screenshot 2021-03-27 173455" src="https://user-images.githubusercontent.com/63475824/112735749-5ace5b80-8f24-11eb-91f4-5b29d861eb9d.png">
<img width="908" alt="Screenshot 2021-03-27 173504" src="https://user-images.githubusercontent.com/63475824/112735750-5ace5b80-8f24-11eb-9794-43e4088b2780.png">
<img width="910" alt="Screenshot 2021-03-27 173513" src="https://user-images.githubusercontent.com/63475824/112735751-5ace5b80-8f24-11eb-9c61-01ff4756931d.png">
<img width="903" alt="Screenshot 2021-03-27 173522" src="https://user-images.githubusercontent.com/63475824/112735752-5ace5b80-8f24-11eb-9d53-4f2405edba7e.png">
<img width="904" alt="Screenshot 2021-03-27 173534" src="https://user-images.githubusercontent.com/63475824/112735753-5ace5b80-8f24-11eb-904f-07d44c8e5be6.png">
<img width="907" alt="Screenshot 2021-03-27 173544" src="https://user-images.githubusercontent.com/63475824/112735754-5b66f200-8f24-11eb-8951-d72aa6df1f73.png">
<img width="910" alt="Screenshot 2021-03-27 173553" src="https://user-images.githubusercontent.com/63475824/112735755-5b66f200-8f24-11eb-9fb3-81a983d0e5e6.png">
<img width="893" alt="Screenshot 2021-03-27 173602" src="https://user-images.githubusercontent.com/63475824/112735756-5b66f200-8f24-11eb-9d5e-8dc0e5aa768d.png">
<img width="898" alt="Screenshot 2021-03-27 173611" src="https://user-images.githubusercontent.com/63475824/112735757-5b66f200-8f24-11eb-8884-5c8b5dfe7afc.png">
<img width="902" alt="Screenshot 2021-03-27 173621" src="https://user-images.githubusercontent.com/63475824/112735758-5b66f200-8f24-11eb-8eab-cfb1144eee71.png">
<img width="903" alt="Screenshot 2021-03-27 173630" src="https://user-images.githubusercontent.com/63475824/112735759-5b66f200-8f24-11eb-80dc-5e8d21b52d48.png">
<img width="907" alt="Screenshot 2021-03-27 173640" src="https://user-images.githubusercontent.com/63475824/112735760-5bff8880-8f24-11eb-8afb-e9be3c61b52d.png">
<img width="908" alt="Screenshot 2021-03-27 173649" src="https://user-images.githubusercontent.com/63475824/112735761-5bff8880-8f24-11eb-9177-8844600e070b.png">
<img width="911" alt="Screenshot 2021-03-27 173659" src="https://user-images.githubusercontent.com/63475824/112735762-5bff8880-8f24-11eb-91d1-bb81feb08a27.png">
<img width="913" alt="Screenshot 2021-03-27 173712" src="https://user-images.githubusercontent.com/63475824/112735763-5bff8880-8f24-11eb-80e6-72ff4cd613a1.png">
<img width="882" alt="Screenshot 2021-03-27 173722" src="https://user-images.githubusercontent.com/63475824/112735765-5bff8880-8f24-11eb-9abf-08241f6606e3.png">
<img width="889" alt="Screenshot 2021-03-27 173732" src="https://user-images.githubusercontent.com/63475824/112735766-5c981f00-8f24-11eb-80ec-d088e3509e95.png">
<img width="868" alt="Screenshot 2021-03-27 173741" src="https://user-images.githubusercontent.com/63475824/112735767-5c981f00-8f24-11eb-9b61-b96d423d471f.png">
<img width="875" alt="Screenshot 2021-03-27 173750" src="https://user-images.githubusercontent.com/63475824/112735769-5c981f00-8f24-11eb-867f-9f7ce62379f1.png">
<img width="888" alt="Screenshot 2021-03-27 173800" src="https://user-images.githubusercontent.com/63475824/112735770-5c981f00-8f24-11eb-9d19-ed9d2b01fb36.png">
<img width="893" alt="Screenshot 2021-03-27 173809" src="https://user-images.githubusercontent.com/63475824/112735771-5c981f00-8f24-11eb-999b-e1d207e4cb79.png">
<img width="872" alt="Screenshot 2021-03-27 173819" src="https://user-images.githubusercontent.com/63475824/112735772-5d30b580-8f24-11eb-928f-e2e0312dcfb8.png">
<img width="881" alt="Screenshot 2021-03-27 173828" src="https://user-images.githubusercontent.com/63475824/112735773-5d30b580-8f24-11eb-8d1d-0078da0a47d9.png">
<img width="892" alt="Screenshot 2021-03-27 173837" src="https://user-images.githubusercontent.com/63475824/112735774-5d30b580-8f24-11eb-964c-e162bb382cd5.png">
<img width="897" alt="Screenshot 2021-03-27 173846" src="https://user-images.githubusercontent.com/63475824/112735775-5d30b580-8f24-11eb-8844-6fb0be25ca43.png">
<img width="878" alt="Screenshot 2021-03-27 173857" src="https://user-images.githubusercontent.com/63475824/112735776-5d30b580-8f24-11eb-8318-e9595998699d.png">
<img width="884" alt="Screenshot 2021-03-27 173907" src="https://user-images.githubusercontent.com/63475824/112735777-5dc94c00-8f24-11eb-9aac-dfe32a1f3566.png">
<img width="886" alt="Screenshot 2021-03-27 173918" src="https://user-images.githubusercontent.com/63475824/112735778-5dc94c00-8f24-11eb-999a-e67e9af1ff47.png">
<img width="895" alt="Screenshot 2021-03-27 173926" src="https://user-images.githubusercontent.com/63475824/112735779-5dc94c00-8f24-11eb-8879-19b4d756e90f.png">
<img width="875" alt="Screenshot 2021-03-27 173935" src="https://user-images.githubusercontent.com/63475824/112735780-5dc94c00-8f24-11eb-81a1-56d45662d5d3.png">

**Comment by SomeDeadGuy** [comment]
Jesus Christ!

**Comment by SomeDeadGuy** [comment]
It is all from pneumatic fun mod.
Will be fixed today.

**Comment by SomeDeadGuy** [comment]
see if it fixed

**Comment by Ichthysdekilt** [comment]
Wow, that was super fast - thank you!  There is only one left now, and I'm only sortakinda thinking it's a tileset thing?
![Screenshot 2021-03-29 134453](https://user-images.githubusercontent.com/63475824/112877794-2f1eb300-9095-11eb-81fa-3e3e9427ac7c.png)

**Comment by SomeDeadGuy** [comment]
Will look at it tomorrow.
Post your modlist, please, so I can recreate it and see this error myself.

**Comment by Ichthysdekilt** [comment]
"dda",
  "no_npc_food",
  "package_bionic_professions",
  "BL9_100monres",
  "crt_expansion",
  "realdarkskies",
  "secronom",
  "aftershock",
  "Arcana",
  "battle_maid",
  "EngineeringEssentials",
  "magiclysm",
  "magicrevamp",
  "bow_opness",
  "More_Survivors_Stories",
  "Nechronica_Redux",
  "PK_REBALANCE",
  "pneumo_fun",
  "mutant_npcs_new",
  "psychiclysm",
  "realdarkskies_faction_balance",
  "wandering_masters",
  "collectablemod",
  "XEAS",
  "rice",
  "AAA",
  "adv_gear",
  "advtech",
  "ArmUpSurvEx",
  "arsenal_breach",
  "Arts' Guns",
  "Tolerate_This",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "Bootleg_Walkers",
  "CBM_Arms",
  "climate_defying_farming",
  "SD_Magcrafting",
  "craftgp",
  "culinary_days_ahead",
  "FIC_Weapons",
  "dried_fruits",
  "ExArch",
  "Uekibati_mod",
  "growable-pots",
  "Gourmand'sGraces",
  "guncotton",
  "homestead",
  "ew_pack",
  "eps_cbm",
  "Locked_and_Loaded",
  "makeshift",
  "Medieval_Mod_Reborn",
  "demon_spider_a",
  "More tea leaf",
  "modern_weapon",
  "MST_Extra",
  "nw_pack",
  "NM_wpns",
  "Pix's Shit",
  "apex",
  "futurearmory",
  "beamswordmod",
  "Soy mod",
  "cool_mod",
  "CerealMod",
  "VermilionMod",
  "thermal_ups",
  "blazemod",
  "vorpal_weapons",
  "WildLiving",
  "Xeno_SAS4",
  "GOV_BANDITS",
  "DracoDogMod",
  "DracoPigMod",
  "jury_rigged_robots",
  "modular_turrets_no_blacklist",
  "mutant_animals",
  "mutant_insects",
  "Salvaged_Robots",
  "Youkai_Disco",
  "light_weariness",
  "MMA",
  "MMA_Mods_Extension",
  "alt_map_key",
  "Cata++",
  "ks_variety_pack",
  "crazy_cataclysm",
  "diluted_mutagens",
  "even_more_mutations",
  "food_irradiator",
  "mxoudpcosmetics",
  "hydroponics",
  "machine",
  "Mining_Mod",
  "more_survivor_notes",
  "more_survivor_stuff",
  "Ninja",
  "recruitment_options",
  "my_sweet_cataclysm",
  "tekitoumap",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "zets_hair_extensions_undead",
  "more_locations",
  "zets_hair_ext_more_locations",
  "zets_hair_ext_pk_rebalance",
  "national_guard_camp_alt",
  "Dorf_Life",
  "ZSFixed_Extended_Buildings",
  "cityside",
  "morlock_village",
  "oa_early_game_mutations_mod",
  "Ships",
  "water_towers",
  "whaleys_tallbuild",
  "cars_to_wrecks",
  "deoxymod",
  "Heavy miners",
  "Tankmod_Revived",
  "necromancy",
  "adv_gearUDP",
  "AftershockUDP",
  "amplified_players_features",
  "AnimatronicsUDP",
  "ArcanaUDP",
  "ArmUpSurvExUDP",
  "Arsenal_BreachUDP",
  "Arts' GunsUDP",
  "battle_maidUDP",
  "BL9_100monresUDP",
  "Bootleg_WalkersUDP",
  "crt_expansionUDP",
  "Cata++UDP",
  "GOV_BANDITS_UDP",
  "CrazyCataclysmUDP",
  "Dorf_LifeUDP",
  "dried_fruitsUDP",
  "ExArchUDP",
  "growable-potsUDP",
  "Gourmand'sGracesUDP",
  "Graphical_Overmap",
  "Graphical_Overmap_SDG_Arcana",
  "Graphical_Overmap_SDG_Cata++",
  "Graphical_Overmap_Magiclysm",
  "Graphical_Overmap_SDG_PK",
  "Graphical_Overmap_SDG_secronom",
  "Graphical_Overmap_SDG",
  "MagiclysmUDP",
  "Medieval_Mod_RebornUDP",
  "Mining_ModUDP",
  "modern_weaponUDP",
  "modular_turrets_no_blacklist_UDP",
  "more_locationsUDP",
  "MST_ExtraUDP",
  "mutant_animalsUDP",
  "mutant_insectsUDP",
  "Mutation_Changes",
  "Mutation_ChangesUDP",
  "My_Sweet_CataclysmUDP",
  "MMAUDP",
  "national_guard_camp_altUDP",
  "PK_REBALANCE_UDP",
  "ProjectKawaii",
  "ProjectKawaii_UDP",
  "Salvaged_RobotsUDP",
  "secronom_UDP",
  "sees_player_retro",
  "Soymod_UDP",
  "Tankmod_RevivedUDP",
  "vamp_stuff_UDP",
  "blazemodUDP",
  "WildLivingUDP",
  "AbrahmsRecipes1",
  "Merchant",
  "Red's Odd Additions",
  "sarcophagi_access",
  "WHALEYHAIR_UDP",
  "autodoc_harmless_perfect",
  "fuji_mpp",
  "More_Military",
  "reapermod",
  "sly_beastfix",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "ZSFIXED_cddaxp"

It's basically Kenan2000's modpack, your tileset, and otopack soundpack on 11548.

**Comment by SomeDeadGuy** [comment]
You do not need to use UDP mods with kenans modpack or latest versions of my tileset. Tiles for mods is already in mod folders.

**Comment by Ichthysdekilt** [comment]
Ohhhhh, I did not know that.  Thank you!

**Comment by SomeDeadGuy** [comment]
last error fixed, check it

**Comment by Ichthysdekilt** [comment]
Thank you, I think that did it!  I also see my chocolate calves again, so #62 can also be closed.  Thanks for everything!
