### ISSUE TITLE
Zets-Hair-Extensions_Undead makes bearded ladies

### ISSUE THREAD

**Issue by 3LD** [SomeDeadGuy/UndeadPeopleTileset#6]
![Untitled](https://user-images.githubusercontent.com/18621502/82619426-ccae7980-9b8a-11ea-896f-fe83f429e31e.png)

**Comment by SomeDeadGuy** [comment]
Oh, in vanilla cataclysm you also has bearded ladies. You just do not see it cause i not setted graphics for it, and you not seeing it in menu cause it is in customization category. I will fix this mod and you will not see it also. It is still going to be there tho, cause game do not understands how to not give ladies a beard during random player generation. :)
