### ISSUE TITLE
Error when loading tileset

### ISSUE THREAD

**Issue by alexsilvestre86** [SomeDeadGuy/UndeadPeopleTileset#60]
Hello, I have just updated the game to the latest stable, redownloaded the tileset and the community modpack, now I am having this error whenever trying to load the game:

 DEBUG    : Error: Json error: <unknown source file>:7:30: invalid escape sequence

    "tiles-new": [
      {
        "file": "mod_tileset\a
                             ^
                              rcana_normal.png",
        "tiles": [
          { "id": "bg_book", "fg": 1, "rotates": false },

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 952

After that the save either refuses to load, or if I change the tileset, it returns to the ASCII default. I opened the \Arcana\mod_tileset\mod_tileset.json file to see if something went wrong or there was a line break as the error message shows, but it looks normal to me, like so:

```
[
  {
    "type": "mod_tileset",
    "compatibility": [ "UNDEAD_PEOPLE_BASE", "UNDEAD_PEOPLE", "MshockRealXotto", "MSX++DEAD_PEOPLE" ],
    "tiles-new": [
      {
        "file": "mod_tileset\arcana_normal.png",
        "tiles": [
          { "id": "bg_book", "fg": 1, "rotates": false },

```

**Comment by SomeDeadGuy** [comment]
Yeah, so weird crap again.
I found the problem, it will be fixed later today.

**Comment by SomeDeadGuy** [comment]
see if it fixed

**Comment by alexsilvestre86** [comment]
Thank  you! I started wondering if the problem was on my end, loading too many mods or something.
I made a test by using the arcana mod's repository version and it worked. 
Just tested it now and it works just fine, so I'll close this. Not too familiar with github yet.
