### ISSUE TITLE
Tileset Error

### ISSUE THREAD

**Issue by FrozenTearCDDA** [SomeDeadGuy/UndeadPeopleTileset#61]
Hey there, yesterday I went too hard, killing zombies at the door of a truck and I set fire to it at some point to kill a SWAT zombie, while there were a ton of items in the ground and I got a tileset error somehow. I don't know what could cause it, but maybe it's something you'd know related to a limit of items. 
![6](https://user-images.githubusercontent.com/15993955/113145573-f43b8d00-9204-11eb-8ce4-40cbfdd4dd65.png)

This is the turn log at the time, but I'm not sure how to get more details of it, I could try if you give me some pointers.

![5](https://user-images.githubusercontent.com/15993955/113145638-0b7a7a80-9205-11eb-80a9-f34a2722d749.png)

**Comment by SomeDeadGuy** [comment]
It is still there or it disappeared after a moment?

**Comment by FrozenTearCDDA** [comment]
Sadly the character died right after the explosion started, so I can't check anymore, just thought I should let you know it happened in those very weird circumstances.

**Comment by SomeDeadGuy** [comment]
Well then I will say it is the same as this issue.
https://github.com/SomeDeadGuy/UndeadPeopleTileset/issues/47
