### ISSUE TITLE
My Sweet Cataclysm - Invisible Calves

### ISSUE THREAD

**Issue by Ichthysdekilt** [SomeDeadGuy/UndeadPeopleTileset#62]
Somehow my cows have become transparent.  I had previously been able to see them, but recently they have changed.
<img width="1223" alt="Chocolate Cows" src="https://user-images.githubusercontent.com/63475824/113367180-57264480-9329-11eb-8e52-0fbefe538a9f.png">

They still leave normal corpses and such, and there are no bug messages.  I've tried both with the update included in the tileset folder, the one in the tileset mods folder, and the one included with Kenan2000's modpack.  I've also redone it on a fresh install using 11552. Is there anything I'm doing wrong?

**Comment by Ichthysdekilt** [comment]
Closed via fix in #59

**Comment by Ichthysdekilt** [comment]
Okay, and now that I did a fresh install they're gone again. I have no idea why.  Install order was Game -> Tileset -> Kenan Mods.  Calves are gone.  Tried Game -> Kenan Mods -> Tileset, still no dice.  :-(

**Comment by SomeDeadGuy** [comment]
Check if it fixed.

**Comment by Ichthysdekilt** [comment]
I can see them - and you made new graphics for them! <3  Thank you!
