### ISSUE TITLE
Secronom Cow is Invisible

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#65]
All other versions of the cow work correctly, except the secronom cow which does not appear for some reason, I looked at the spritesheets and the sprite is indeed there, however it seems the sprite is not activating in game.

**Comment by Theawesomeboophis** [comment]
It appears that it is a issue with compatibility with the kenan spritesheet, I will replace the pngs from kenan with the pngs from this tileset as a temporary fix.

**Comment by SomeDeadGuy** [comment]
Don't see how it is my issue, lol.
Just tested tiles for mod and with or without mod tileset and everything with flesh cows looks correct. Gonna be clossing this.

**Comment by Theawesomeboophis** [comment]
It's not, it's a problem with kenan modpack not being updated at the
moment, I just forgot to close this.

**Comment by SomeDeadGuy** [comment]
Sure, no problem.
