### ISSUE TITLE
MSC Unsprited Creatures and Terrain

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#66]
Creatures and objects from below PRs are currently unsprited.
https://github.com/CleverRaven/Cataclysm-DDA/pull/45383
https://github.com/CleverRaven/Cataclysm-DDA/pull/45151

**Comment by SomeDeadGuy** [comment]
added those

**Comment by Theawesomeboophis** [comment]
Thanks.
