### ISSUE TITLE
secronom all flesh monster or building tiles are not shown correctly

### ISSUE THREAD

**Issue by MikuMiddo** [SomeDeadGuy/UndeadPeopleTileset#68]
![image](https://user-images.githubusercontent.com/53809752/115319103-a71e5b80-a1b1-11eb-9059-cafbd3c9f301.png)
this is the flesh city and you can see the flesh covered window is shown wrongly
![image](https://user-images.githubusercontent.com/53809752/115319189-d1701900-a1b1-11eb-928a-9da227c36a9a.png)
And all the monster are seems strange，and this is what a charger zombie looks like
![image](https://user-images.githubusercontent.com/53809752/115319283-011f2100-a1b2-11eb-80c9-b794e527136e.png)
Hope you can fix this soon ,So I can continue explore the flesh city :D.

**Comment by SomeDeadGuy** [comment]
Come on, dude.
What game are you playing? DDA or BN?
What version of the secronom are you using?
Are you using Tileset Mod or not?
Cause my secronom of the latest version does not look like this.
![Secro_Fine](https://user-images.githubusercontent.com/37592026/115343044-ec438d00-a1b3-11eb-953d-080483d3d0f1.PNG)

**Comment by SomeDeadGuy** [comment]
Hello?

**Comment by MikuMiddo** [comment]
> Hello?

Sorry for that,I haven't check my email for days.
I found out I am using kenan mod pack,so the mod in data/mods aren't been correctly override,I just put them into the modpack and It's fine now,sorry for disturb.  :P
