### ISSUE TITLE
Spear floating away from character

### ISSUE THREAD

**Issue by TheLyca0n** [SomeDeadGuy/UndeadPeopleTileset#69]
Latest version seems to have copper/stone spears floating away from the character sprite. Doesn't impact any other non spear related items but will have to test a couple more

**Comment by SomeDeadGuy** [comment]
Yes, my guy Shangxin on discord developing new script for automatic wielded items graphics redestribution.
I uploaded tileset generated with this script to find bugs.
Will be fixed later today. Sorry for inconvinience.

**Comment by TheLyca0n** [comment]
> 
> 
> Yes, my guy Shangxin on discord developing new script for automatic wielded items graphics redestribution.
> I uploaded tileset generated with this script to find bugs.
> Will be fixed later today. Sorry for inconvinience.

It's no big, appreciate the work you do man

**Comment by SomeDeadGuy** [comment]
Check if it fixed!

**Comment by SomeDeadGuy** [comment]
Hello?

**Comment by TheLyca0n** [comment]
It's fixed on all the items I tested. Nice one
