### ISSUE TITLE
Misplaced Indicators

### ISSUE THREAD

**Issue by heretic01** [SomeDeadGuy/UndeadPeopleTileset#70]
![Снимок экрана (1)](https://user-images.githubusercontent.com/54194189/116186086-9e86d180-a72b-11eb-8b72-3d9be7142b01.png)
![Снимок экрана (2)](https://user-images.githubusercontent.com/54194189/116186090-9fb7fe80-a72b-11eb-8cf2-4e32e9812e21.png)
![Снимок экрана (3)](https://user-images.githubusercontent.com/54194189/116186092-a0509500-a72b-11eb-838e-644f586236d2.png)
![Снимок экрана (4)](https://user-images.githubusercontent.com/54194189/116186094-a0509500-a72b-11eb-8f8d-310cdb307f61.png)

I`d love to know what causes this bug

**Comment by SomeDeadGuy** [comment]
Do not use MSX Hide Debug and MSX Hide STATUS
