### ISSUE TITLE
SDG Font Not Working On Mobile

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#71]
The Larwick_SDG font for graphical overmap does not work on android version of cataclysm, regular Graphical overmap works fine, not sure why the other fonts don't work( Other fonts besides Larwick default don't work on android either, just Larwick.PNG)

**Comment by Theawesomeboophis** [comment]
Autocorrect is dumb and replaced font with don't.

**Comment by SomeDeadGuy** [comment]
overmap mod is for pc only
if it is not working on android it is not something i would assumed will work when i made it
if you have a solution to this problem reopen this issue

**Comment by Theawesomeboophis** [comment]
Ok, I will use regular graphical overmap on mobile and continue to use SDG
font on PC.

**Comment by SomeDeadGuy** [comment]
Try putting my font pngs in data/fonts and changing the lines in fonts.json according to where font is now located to see if it works.
I remember talking with Axema about this issue on android, we haven't fond a solution ether.

**Comment by Theawesomeboophis** [comment]
I will attempt that

**Comment by Theawesomeboophis** [comment]
Adding Android/ in front had no effect ( I did this as mobile files have
same name as PC files, except instead of being in a drive, they are in a
folder called Android).

**Comment by Theawesomeboophis** [comment]
How did Larwick get regular graphical overmap to work on mobile, Is it
something to do with C++ or can it be done in Json?
