### ISSUE TITLE
.223 Weapons displaying incorrect wielded sprites

### ISSUE THREAD

**Issue by Theawesomeboophis** [SomeDeadGuy/UndeadPeopleTileset#73]
Most weapons using .223 ammo ( 2 use correct sprites) are not showing correct sprites and look like picture in issue below.
Affected sprites include the .223 revolver rifle and most of the other .223 rifles.
Not sure if other rifles are affected, will test more soon.

**Comment by Theawesomeboophis** [comment]
Related to https://github.com/SomeDeadGuy/UndeadPeopleTileset/issues/1

**Comment by Theawesomeboophis** [comment]
Most of these weapons are from Cata++ it seems. Gonna see where the rest are from,

**Comment by Theawesomeboophis** [comment]
Affected tiles:
Bolt Action .223 Rifle
Lever Action .223 Rifle
Pipe Rifle .223
Pump Action .223 Rifle
Survivor's .223 LMG

**Comment by SomeDeadGuy** [comment]
It is from Fallout CDDA mod.

**Comment by Theawesomeboophis** [comment]
Ok, I tried finding what mod it was from and I couldn't, thank you.

**Comment by SomeDeadGuy** [comment]
cata++ and fallout mod updated
see if problem completely fixed

**Comment by Theawesomeboophis** [comment]
Ok, I'll  test it and report back.

**Comment by Theawesomeboophis** [comment]
It works, thanks
