### ISSUE TITLE
Bald Black Dragon

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [SomeDeadGuy/UndeadPeopleTileset#75]
I apologize for contacting you, I certainly understand that the Magiclysm add-on is still in development, but can you make the Black Dragon Mutation in the full release ... less bald? Add a comb, which the same reptiles have, or so that the ears / horns, when mutated, are already superimposed on top of the black scales, otherwise if they work out, they turn out to be behind and they are poorly and ugly visible
Plus, I noticed that with black scales, the claws on the hands of the character are not visible, or teeth sometimes, somebuilds
https://imgur.com/a/HKhsJm1

**Comment by SomeDeadGuy** [comment]
check how dragon looks now

**Comment by ZSHADOWWOLF** [comment]
> 
> 
> check how dragon looks now

Yaay, it looks so cool, and so cute! Thank you!
