### ISSUE TITLE
Instalation process for mods is impossible to follow

### ISSUE THREAD

**Issue by ChewedGum** [SomeDeadGuy/UndeadPeopleTileset#76]
I don't understand how to make this tileset to work with other mods, like magiclysm.
The instructions are all over the place, i don't understand any of it.
Can you please make step by step guide/explanation? Thank you in advance.

**Comment by Theawesomeboophis** [comment]
Take the data and gfx folders from this tileset and copy and paste them into your Cataclysm install ( wherever that is on your computer).

**Comment by ChewedGum** [comment]
Ok i see now. There was a confusion because i have the launcher, the one that updates the game, so it itself has this instalation folder, but there's also a folder of the current version and the one for the program that updates everything and hosts all my downloaded versions of the games in it.
Anyway, thank you.

**Comment by Theawesomeboophis** [comment]
I use launcher as well and the method above works, if there's anything you still don't understand, feel free to ask.

**Comment by SomeDeadGuy** [comment]
> impossible to follow
For you.
