### ISSUE TITLE
Tiles Missing on many map areas, notably roads. Played on 0.F

### ISSUE THREAD

**Issue by Eneocho** [SomeDeadGuy/UndeadPeopleTileset#77]
What the title says, roads and riverbanks are missing in the map.

**Comment by SomeDeadGuy** [comment]
Yep, working on it.

**Comment by Eneocho** [comment]
> 
> 
> Yep, working on it.

Appreciated.

**Comment by Eneocho** [comment]
@SomeDeadGuy I have a question but don't wanna open a new issue. Diagonal roads have that zig-zag pattern to it. Is this a stylistic choice? Because I've seen some tilesets that have smooth diagonals on roads (which to my opinion look better).

**Comment by SomeDeadGuy** [comment]
You mean in game, not on the map? It is a choice. See end of the roads in towns, if i make diagonal smooth there will be corners cuts everywhere where asphalt road meets street sidewalk.
If you about the map then yes, i saw those zig-zag patters and this i think i will make smooth.

**Comment by Eneocho** [comment]
I did mean in game, yeah. But again, I've seen tilesets in which "corners cuts everywhere where asphalt road meets street sidewalk." don't happen on the sidewalk.

**Comment by SomeDeadGuy** [comment]
It does. You just not looking in the right places.

**Comment by SomeDeadGuy** [comment]
fixed

**Comment by Eneocho** [comment]
> 
> fixed

Related: https://www.youtube.com/watch?v=sAXZbfLzJUg
