### ISSUE TITLE
double tiles houses

### ISSUE THREAD

**Issue by DesLandysh** [SomeDeadGuy/UndeadPeopleTileset#78]
in 0.E.3 (as is in Graphic mod for map) there wasn't indicators to double tiled houses (esp. magician's homes for magiclysm) and they'd drawn as vv, ^^, and etc, as duplex itself in vanilla.
have you any thoughts to fix this?

I'd waited for update the UndeadPeople tileset to check new 0.F version

**Comment by SomeDeadGuy** [comment]
closed due to i no longer gonna support graphical overmap mod in favor of graphical overmap in dda
