### ISSUE TITLE
adding quick download links to the readme

### ISSUE THREAD

**Issue by FONZACUS** [SomeDeadGuy/UndeadPeopleTileset#81]
(sorry, im still a noob with git|hub)

is it alright to have quick DL links for the gfx folders via [downgit](https://minhaskamal.github.io/DownGit)?

if you click on any of these links, itll start the download for the preferred edition

[current](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/SomeDeadGuy/UndeadPeopleTileset/tree/master/TILESETS/gfx/MSX%2B%2BUnDeadPeopleEdition)
[legacy](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/SomeDeadGuy/UndeadPeopleTileset/tree/master/TILESETS/gfx/MSX%2B%2BUnDeadPeopleEditionLegacy)
[MXR](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/SomeDeadGuy/UndeadPeopleTileset/tree/master/TILESETS/gfx/MshockXotto%2BREAL)

these could be later expanded for further quick links

**Comment by SomeDeadGuy** [comment]
i do not want people downloading something else and then complaning here or on my discord channel
use your brain and figure this shit out
thank you tho for your work, i appreciate it

**Comment by FONZACUS** [comment]
none of it is something else, it just downloads the 1 of the 3 folders as a zip from you/repo/tree/master/tilesets/gfx.

**Comment by SomeDeadGuy** [comment]
I mean people will download main tileset only and then complain what there is no tilesets for mods. I want installation to be same for everybody.
