### ISSUE TITLE
Run/Crouch/Prone indicators are sometimes harder to see than they should be.

### ISSUE THREAD

**Issue by ifffrt** [SomeDeadGuy/UndeadPeopleTileset#83]
Sometimes they blend in with the background at high zoom settings and makes me forget I was running. I think the problem is that they are both transparent and grey. Maybe making it white and opaque would be better? EDIT: I just tested out with making it white but not opaque and I thought it was visible enough like that. It overlaps the bleed indicator though.

**Comment by SomeDeadGuy** [comment]
but it will look so bizzare i think.
Provide screenshots so i can see what it looks better.

**Comment by ifffrt** [comment]
Here they are. One is with the bleed indicator. One is without.
![New Bitmap Image](https://user-images.githubusercontent.com/74819253/129401461-0c37de63-2345-4ab5-be3e-064b78e12ebb.png)
![New Bitmap Image (2)](https://user-images.githubusercontent.com/74819253/129401469-790c46ea-e0be-4de5-9b2c-c90b45a5057d.png)
Here's another one with the downed indicator.
![New Bitmap Image (3)](https://user-images.githubusercontent.com/74819253/129401802-1f60e235-754c-4131-9abb-4c4fe2970702.png)

I think it looks ok without anything around it. But the overlapping is a bit of a problem. Maybe it could be made to be more transparent? Or maybe set it a bit further to the right?

**Comment by SomeDeadGuy** [comment]
check how it is now

**Comment by ifffrt** [comment]
New indicators are excellent. Thanks. This issue can be closed now.
