### ISSUE TITLE
Found a missing graphics glitch with the basic, standard item tiles

### ISSUE THREAD

**Issue by RandDenner** [SomeDeadGuy/UndeadPeopleTileset#84]
If you (a)ctivate a motorcycle helmet, it converts to another item with the (open visor) state.
It has no graphic for being worn, so is invisible, and dropping that version of the helmet shows ASCII, not a graphic.
As you can see in the picture, below:
(top: visor normal, bottom: visor raised)
(both are while wearing a headlamp and glasses)
![CDDA helmet](https://user-images.githubusercontent.com/73523034/129955868-20196c4f-3e9b-44ed-9cbb-5f545bcdca5b.png)
![image](https://user-images.githubusercontent.com/73523034/129957053-90cb12a1-e3e2-48cd-9d76-50602bf48c59.png)

**Comment by SomeDeadGuy** [comment]
should be fixed

**Comment by SomeDeadGuy** [comment]
please review it and say if it is cool, thank you :)

**Comment by RandDenner** [comment]
I think it's really good.

Thank you!
